### ISSUE TITLE
suggesting IEEE competitions

### ISSUE THREAD

**Issue by joeljosephjin** [seungjaeryanlee/awesome-rl-competitions#4]
https://cis.ieee.org/conferences/competitions

this contains many ongoing AI competitions.

Thanks for creating and maintaining this repo. Its helpful. :)

**Comment by seungjaeryanlee** [comment]
Thank you for your kind words and your suggestions! I will add them soon :)

**Comment by seungjaeryanlee** [comment]
They should all be included now, except for AIBirds which I can't access their website. Thank you!
