### ISSUE TITLE
[Suggestion] Restarted competitions - flatland

### ISSUE THREAD

**Issue by kharitonov-ivan** [seungjaeryanlee/awesome-rl-competitions#5]
Hey! Everything old is new again!
https://www.aicrowd.com/challenges/neurips-2020-flatland-challenge/

Thanks for this repo!

**Comment by seungjaeryanlee** [comment]
Thank you @neer201! Good to hear that the Flatland Challenge is back in NeurIPS. Do you happen to know when the competition begins and ends? I couldn't find the information on the AICrowd website.

**Comment by kharitonov-ivan** [comment]
@seungjaeryanlee I see only this. Today, 01 June 2020, 72 days left. Status - hidden.
![image](https://user-images.githubusercontent.com/25615790/83436260-3578da00-a446-11ea-8794-e934be006369.png)

**Comment by seungjaeryanlee** [comment]
@neer201 Looks like the information hasn't been added yet then. I added a row with the start and end dates empty for now. Again, thank you for the suggestion!
