### ISSUE TITLE
 [Suggestion] ML5G-PHY-Reinforcement learning: scheduling and resource allocation”

### ISSUE THREAD

**Issue by felipebastosb** [seungjaeryanlee/awesome-rl-competitions#7]
The Federal University of Pará (UFPA) and the International Telecommunications Union (ITU) are hosting a ML/RL challenge in order to solve 5G and B5G problemns. The registration deadline is 31 August 2021.

More information can be found at this link: https://ai5gchallenge.ufpa.br/

**Comment by seungjaeryanlee** [comment]
Thank you for your suggestion! The competition has been added.
